version: 1
formatters:
  simple:
    format: '%(asctime)s %(module)s.%(funcName)s(%(lineno)d)-%(levelname)s  %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: simple
      filename: ./logs/info.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8

  error_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: simple
      filename: ./logs/error.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8

loggers:
  simpleExample:
    level: DEBUG
    handlers: [console]
    propagate: no

root:
  level: DEBUG
  handlers: [console, info_file_handler]